### PR TITLE
Revert tool version

### PR DESCRIPTION
**Pull request by activehigh**
I think this will fix the broken build. @alphashaw

### CODE REVIEW

**Comment by alphashaw** [comment]
Yeah. 
The build error (controller-gen binary not found) seem strange.
Did you know of a reason why it couldn’t be installed after the first Make target was ran? 
Eventually, we may have to upgrade.

**Comment by alphashaw** [comment]
The error seems to be persisting.
For some reason, I can’t run a “docker build” locally here with my current device.
Can it also be related to the “go” version?

**Comment by activehigh** [comment]
Still failing.  It seems like it's looking for the file inside the container. yeah I am confused too. it should have downloaded it when make is run. It could be a permission issue. I will see if I can make it work when I get some free time.

> The error seems to be persisting. For some reason, I can’t run a “docker build” locally here with my current device. Can it also be related to the “go” version?

**Comment by activehigh** [comment]
Found the issue. `go get tools` was removed in golang 1.18. https://github.com/kubernetes-sigs/kubebuilder/issues/2692#issuecomment-1129939566

So to keep things going forward we probably need to use `go install` instead of `go get tools`.

> The error seems to be persisting. For some reason, I can’t run a “docker build” locally here with my current device. Can it also be related to the “go” version?

Added new syntax in here https://github.com/monimesl/istio-virtualservice-merger/pull/6

**Pull request merged**
