### PR TITLE
Feature/sre 000 fix broken watch

### PR DESCRIPTION
**Pull request by activehigh**
- Fix the watch method. Having a `for` call is mandatory.

### CODE REVIEW

**Comment by alphashaw** [comment]
Sorry. I have been busy and didn't notice this quickly.
I think this is great!!
I will go through it in a few days time to see how it can be merged safely.

Thanks

**Comment by activehigh** [comment]
Haha, I actually accidentally opened it against the main repo, I was supposed to raise against our forked one, at Rokt. 

But of course, by any means if you feel that these changes are making it better, happy to contribute. 

It is a great component, we like it. So we are making it more stable in our fork for teams to use it. 


> Sorry. I have been busy and didn't notice this quickly.
> 
> I think this is great!!
> 
> I will go through it in a few days time to see how it can be merged safely.
> 
> 
> 
> Thanks

**Comment by activehigh** [comment]
I will close this one and open a separate one from the master branch. that has the changes with the metrics.

> Sorry. I have been busy and didn't notice this quickly. I think this is great!! I will go through it in a few days time to see how it can be merged safely.
> 
> Thanks

**Comment by activehigh** [comment]
@alphashaw Opened a new PR with all changes made in our fork, would really appreciate your review - https://github.com/monimesl/istio-virtualservice-merger/pull/4

**Pull request closed without merging**
